[package]
name = "thegrep"
version = "1.0.0"
authors = ["Vincent Enierga <venierga@email.unc.edu>"]
edition = "2018"

[dependencies]
structopt = {version = "0.2", default-features = false }
rand = "0.6"
